# Generated by Django 3.1.6 on 2021-02-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openidcuser',
            name='usertype',
            field=models.CharField(choices=[('staff', 'Staff'), ('undergrad', 'Undergrad'), ('postgrad', 'Postgrad'), ('office', 'Office'), ('conted', 'Conted'), ('summer', 'Summer'), ('web', 'Web'), ('temporary', 'Temporary'), ('unknown', 'Unkown')], max_length=50),
        ),
    ]
