# Generated by Django 3.1.6 on 2021-02-10 20:53

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenIDCUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', login.models.OpenIDCUserManager()),
            ],
        ),
    ]
