# Generated by Django 3.1.6 on 2021-02-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_openidcuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='aber_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.openidcuser'),
            preserve_default=False,
        ),
    ]
