# Generated by Django 3.1.6 on 2021-02-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_discorduser_aber_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='aber_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aber_id', to='login.openidcuser'),
        ),
    ]
