# Generated by Django 3.1.6 on 2021-02-11 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210211_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discorduser',
            old_name='aber_id',
            new_name='openidc',
        ),
    ]
