# Generated by Django 3.1.6 on 2021-02-16 17:35

from django.db import migrations, models
import login.managers


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210211_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('login.openidcuser',),
            managers=[
                ('objects', login.managers.OpenIDCUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Undergrad',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('login.openidcuser',),
            managers=[
                ('objects', login.managers.OpenIDCUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='openidcuser',
            name='usertype',
            field=models.CharField(choices=[('staff', 'Staff'), ('undergrad', 'Undergrad')], max_length=50),
        ),
    ]
