# Generated by Django 3.1.6 on 2021-02-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210217_1517'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='openidcuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='openidcuser',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='openidcuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='openidcuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
