# Generated by Django 3.1.6 on 2021-02-18 11:14

from django.db import migrations
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20210217_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Undergrad',
        ),
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', login.models.DiscordUserOAuth2Manager()),
            ],
        ),
    ]
